brew "git"
brew "neovim"
brew "tmux"
brew "fzf"
brew "ripgrep"
brew "fd"
brew "tree-sitter"

cask "ghostty"
cask "zen-browser"
cask "raycast"
cask "karabiner-elements"
cask "nikitabobko/tap/aerospace"
cask "figma"
cask "spotify"
