set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on

unbind C-Space
set-option -g prefix C-Space
bind-key C-Space send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n 'C-1' select-window -t 1
bind -n 'C-2' select-window -t 2
bind -n 'C-3' select-window -t 3
bind -n 'C-4' select-window -t 4
bind -n 'C-5' select-window -t 5
bind -n 'C-6' select-window -t 6
bind -n 'C-7' select-window -t 7
bind -n 'C-8' select-window -t 8
bind -n 'C-9' select-window -t 9
